// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Hestia.CompiledModels
{
    public partial class HestiaDbContextModel
    {
        private HestiaDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b7742932-0904-4224-b6d3-a62158070f0f"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var toDoEntity = ToDoEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            ToDoEntityEntityType.CreateAnnotations(toDoEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
