// <auto-generated />
using Hestia.CompiledModels;
using Hestia.Services;
using Microsoft.EntityFrameworkCore.Infrastructure;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(HestiaDbContext), typeof(HestiaDbContextModel))]
