// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Hestia
{
    public partial class HestiaDbContextModel
    {
        private HestiaDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("286acc0a-6cd8-4d46-8fbb-dcd3951617ab"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var toDoEntity = ToDoEntityEntityType.Create(this);
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            ToDoEntityEntityType.CreateAnnotations(toDoEntity);
            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
